app = "quizapp"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--max-old-space-size=4096"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"

[machine]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1 