[build]
builder = "nixpacks"
buildCommand = "NODE_OPTIONS='--max-old-space-size=4096' bun run build"

[deploy]
startCommand = "node .output/server/index.mjs"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_VERSION = "20"
NODE_OPTIONS = "--max-old-space-size=4096" 